name: financehero
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  lottie: ^3.3.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  google_fonts: ^6.2.1
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  firebase_database: ^11.3.5
  firebase_core: ^3.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/